# permissions for end users to view demovolumes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: demovolumes-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: demo-operator
    app.kubernetes.io/part-of: demo-operator
    app.kubernetes.io/managed-by: kustomize
  name: demovolumes-viewer-role
rules:
- apiGroups:
  - demo.demo.kubebuilder.io
  resources:
  - demovolumes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - demo.demo.kubebuilder.io
  resources:
  - demovolumes/status
  verbs:
  - get
