# permissions for end users to edit demovolumes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: demovolumes-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: demo-operator
    app.kubernetes.io/part-of: demo-operator
    app.kubernetes.io/managed-by: kustomize
  name: demovolumes-editor-role
rules:
- apiGroups:
  - demo.demo.kubebuilder.io
  resources:
  - demovolumes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - demo.demo.kubebuilder.io
  resources:
  - demovolumes/status
  verbs:
  - get
